# Dvě kritéria

Připravujeme seznam potravin pro účely lékařského výzkumu, který se bude zabývat kardiovaskulárním systémem. Chceme vybrat potraviny, které splňují dvě kritéria:

 nízký obsah nasycených mastných kyselin ("Fatty acids, total saturated", uvažuj méně než 1 gram),
 vysoký obsah vlákniny ("Fiber, total dietary", uvažuj více než 4 gramy).
 Zatímco nasycené mastné kyseliny jsou považovány za spíše škodlivé pro kardiovaskulární systém, vláknina je považována spíše za prospěšnou.

Nejprve je potřeba napsat dotaz, který potraviny vybere. Dotaz je poměrně složitý, ale později si v rámci kurzu ukážeme, jak takovou úlohu vyřešit jednodušeji. Je potřeba použít operátor & i | a závorky, pomocí kterých řídíme, které podmínky se vyhodnocují spolu. Níže jsou rozepsané podmínky, které budeme potřebovat:

Ve sloupci "name" musí být hodnota "Fatty acids, total saturated" a současně ve sloupci "amount" hodnota menší než 1. Mezi tyto podmínky vložíme operátor &, protože musí být splněné obě.
Ve sloupci "name" musí být hodnota "Fiber, total dietary" a současně ve sloupci "amount" hodnota vetší než 4. Mezi tyto podmínky vložíme operátor &, protože musí být splněné obě.
Protože obě výživné látky jsou na samostatném řádku, musíme mezi obě podmínky dát operátor |. Pokud nějaká potraviny splňuje obě podmínky, bude tedy ve výsledné tabulce dvakrát. Pokud splňuje pouze jednou z podmínek, bude ve výsledné tabulce pouze jednou. Počet výskytů potraviny ve výsledné tabulce můžeme ověřit pomocí metodu values_count().

U kombinace operátorů & a | je vhodné uvědomit si, v jaké prioritě by měly být používány. Ač to zní složitě, je to pojem, který už známe z úvodního kurzu z příkladu, kde jsme používali násobení a sčítání v jednom příkladu. Pro operátory & a | platí, že operátor & máš vyšší prioritu než |. To nám vyhovuje, protože my chceme nejprve vyhodnotit podmínky s operátorem & a poté spojit výsledky s využitím opretáro |.

Níže je tedy struktura, kterou je potřeba upravit, aby řešila popsané podmínky.

   - food_nutrient_filtered = food_nutrient[(ve sloupci "name" je hodnota "Fatty acids, total saturated") & (ve sloupci "amount" je hodnota menší než 1) |
                        (ve sloupci "name" je hodnota "Fiber, total dietary") & (ve sloupci "amount" je hodnota větší než 4)]
                        
Pokud se úvaze o priotách chceš vyhnout, je možné to vyřešit přidanými závorkami. Tyto závorky nijak neovlivňují, jak Python příkaz vyhodnotí, ale můžou zlepšit čistelnost a pochopitelnost příkazu pro člověka.

   - food_nutrient_filtered = food_nutrient[((ve sloupci "name" je hodnota "Fatty acids, total saturated") & (ve sloupci "amount" je hodnota menší než 1)) |
                        ((ve sloupci "name" je hodnota "Fiber, total dietary") & (ve sloupci "amount" je hodnota větší než 4))]

### Řešení

In [ ]:
import pandas as pd

food_nutrients = pd.read_csv('food_nutrient.csv')
food_nutrients.info()

In [8]:
food_nutrient_filtered = food_nutrients[(food_nutrients['name'] == 'Fatty acid, total saturated') & (food_nutrients['amount'] < 1) | (food_nutrients['name'] == 'Fiber, total dietary') & (food_nutrients['amount'] > 4)]
food_nutrient_filtered

,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,loq,footnote,min_year_acquired,name,unit_name
83630,1107295,1079,6.7,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
83635,1108349,1079,8.8,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
83638,1109116,1079,7.1,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
83639,1109336,1079,10.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
83642,1109434,1079,7.1,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
...,...,...,...,...,...,...,...,...,...,...,...,...,...
91604,2655540,1079,4.2,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
91608,2655929,1079,7.5,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
91609,2656307,1079,9.4,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
91623,2659199,1079,5.4,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
91629,2660613,1079,10.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G

In [10]:
food_nutrient_filtered['name'].value_counts()

name
Fiber, total dietary    1682
Name: count, dtype: int64

In [9]:
# nebo

food_nutrient_filtered_2 = food_nutrients[((food_nutrients['name'] == 'Fatty acid, total saturated') & (food_nutrients['amount'] < 1)) | ((food_nutrients['name'] == 'Fiber, total dietary') & (food_nutrients['amount'] > 4))]
food_nutrient_filtered_2

,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,loq,footnote,min_year_acquired,name,unit_name
83630,1107295,1079,6.7,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
83635,1108349,1079,8.8,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
83638,1109116,1079,7.1,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
83639,1109336,1079,10.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
83642,1109434,1079,7.1,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
...,...,...,...,...,...,...,...,...,...,...,...,...,...
91604,2655540,1079,4.2,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
91608,2655929,1079,7.5,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
91609,2656307,1079,9.4,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
91623,2659199,1079,5.4,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G
91629,2660613,1079,10.0,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fiber, total dietary",G